method: 'grid'
name: 'earlyfusion'
metric: 
    name: 'val_accuracy'
    goal: 'maximize'   

parameters: 
    seed:
      value: 42 
    model:
      value: 'EarlyFusion'
    data:
      value: 'mosei'

    # optimizer
    lr: 
      value: 3e-4
    weight_decay: 
      value: 1e-5

    # model parameters
    n_classes:
      value: 7
    input_size:
      value: 768
    hidden_size:
      value: 256
    proj_size:
      value: 256
    fine_tune:
      value: True
    marlin_model: 
      value: 'marlin_vit_base_ytf'

    batch_size:
      value: 4
    strategy:
      value: 'ddp_find_unused_parameters_true'
    precision:
      value: 16
    epoch:
      value: 1

    ckpt:
      value: 'ckpt/early_fusion/test'

    