method: 'grid'
name: 'gatefusion'
metric: 
    name: 'val_accuracy'
    goal: 'maximize'   

parameters: 
    seed:
      value: 0

    model:
      value: 'GatedFusion'

    data:
      value: 'mosei'

    # optimizer
    lr: 
      values: [5e-5, 3e-4]
    weight_decay: 
      value: 1e-5

    # model hparams
    dim_out:
      value: 256
    n_classes:
      value: 6
    input_size:
      value: 768
    hidden_size:
      value: 256
    proj_size:
      value: 256
    fine_tune:
      value: True
    marlin_model: 
      value: 'marlin_vit_base_ytf'

    # trainer hparams
    batch_size:
      value: 4
    epoch:
      value: 20
    strategy:
      value: 'ddp_find_unused_parameters_true' # 'ddp'
    precision:
      value: 16
    

    # checkpoint root dir
    ckpt:
      value: 'ckpt/mosei/gated_fusion_v2/'

    