method: 'grid'
name: 'gatefusion'
metric: 
    name: 'val_accuracy'
    goal: 'maximize'   

parameters: 
    seed:
      value: 0

    model:
      value: 'GatedFusion'

    # optimizer
    lr: 
      values: [3e-5, 3e-4]
    weight_decay: 
      value: 1e-5

    # model hparams
    dim_out:
      value: 256
    n_classes:
      value: 6
    input_size:
      value: 512
    hidden_size:
      value: 256
    proj_size:
      value: 256
    fine_tune:
      value: True

    # trainer hparams
    batch_size:
      value: 2
    devices:
      value: 2
    epoch:
      value: 10
    strategy:
      value: 'ddp_find_unused_parameters_true' # 'ddp'
    precision:
      value: 16
    marlin_model: 
      value: 'marlin_vit_base_ytf'

    # checkpoint root dir
    ckpt:
      value: 'ckpt/gated_fusion_tanh'

    