method: 'grid'
metric: 
    name: 'val_accuracy'
    goal: 'maximize'   

parameters: 
    seed:
      value: 0
    model:
      value: 'hubert-large'

    lr: 
      values: [5e-5, 3e-5]
    weight_decay: 
      value: 1e-5
  
    # hubert parameters
    num_labels:
      value: 6

    batch_size:
      value: 32

    devices:
      value: 1

    precision:
      values: [32, 16]
    
    epoch:
      value: 10

    ckpt:
      value: 'ckpt/hubert-large-best/seed0'