method: 'grid'

metric: 
    name: 'val_accuracy'
    goal: 'maximize'   

parameters: 
    seed:
      value: 42 

    lr: 
      values: [3e-4, 5e-4, 3e-5, 1e-3]
    weight_decay: 
      value: 1e-5
  
    # lstm parameters
    hidden_size:
      value: 128
    output_size:
      value: 6


    batch_size:
      value: 32

    devices:
      value: 1
    
    epoch:
      value: 100

    ckpt:
      value: 'ckpt-lstm'