method: 'grid'
name: 'LSTM'
metric: 
    name: 'val_accuracy'
    goal: 'maximize'   

parameters: 
    seed:
      value: 42 

    model:
      value: 'LSTMModel'
    data:
      value: 'mosei'
    fine_tune:
      value: False

    # optimizer parameters
    lr: 
      values: [3e-4, 5e-4, 3e-5, 1e-3]
    weight_decay: 
      value: 1e-5
  
    # lstm parameters
    feature:
      value: 'spectrogram'
    input_size:
      value: 128
    hidden_size:
      values: [256, 128]
    n_classes:
      value: 7

    # trainer
    batch_size:
      value: 32
    strategy:
      value: 'ddp'
    precision:
      value: 32
    
    epoch:
      value: 20

    ckpt:
      value: 'ckpt/lstm/au17'