method: 'grid'
name: 'marlin'
metric: 
    name: 'val_accuracy'
    goal: 'maximize'   

parameters: 
    seed:
      value: 0

    model:
      value: 'MarlinForClassification'

    data:
      value: 'cremad'

    # optimizer
    lr: 
      values: [3e-4, 3e-5]
    weight_decay: 
      value: 1e-5

    hidden_size:
      value: 512
    proj_size:
      value: null
    fine_tune:
      value: True
    marlin_model:
      values: ['marlin_vit_base_ytf', 'marlin_vit_large_ytf'] #'marlin_vit_small_ytf'  'marlin_vit_large_ytf'
    n_classes:
      value: 6

    # trainer
    batch_size:
      value: 2
    strategy:
      value: 'ddp'
    precision:
      value: 16
    
    epoch:
      value: 20

    ckpt:
      value: 'ckpt/marlin_fine_tune'