method: 'grid'

metric: 
    name: 'val_accuracy'
    goal: 'maximize'   

parameters: 
    seed:
      value: 0

    model_name:
      value: 'marlin'

    lr: 
      values: [5e-5, 3e-5]
    weight_decay: 
      value: 1e-5

    hidden_size:
      value: 512

    fine_tune:
      value: True
  
    model:
      values: 'marlin_vit_base_ytf' #'marlin_vit_small_ytf'  'marlin_vit_large_ytf'
    n_classes:
      value: 6

    batch_size:
      value: 2

    devices:
      value: 2
    
    epoch:
      value: 20

    ckpt:
      value: 'ckpt/marlin_fine_tune_16'