method: 'grid'
name: 'marlin'
metric: 
    name: 'val_accuracy'
    goal: 'maximize'   

parameters: 
    seed:
      value: 0

    model:
      value: 'MarlinForClassification'

    data:
      value: 'mosei'

    # optimizer
    lr: 
      value: 3e-4
    weight_decay: 
      value: 1e-5

    hidden_size:
      value: 512
    proj_size:
      value: null
    fine_tune:
      value: True
    marlin_model:
      value: 'marlin_vit_small_ytf' #'marlin_vit_base_ytf'  'marlin_vit_large_ytf'
    n_classes:
      value: 7

    # trainer
    batch_size:
      value: 8
    strategy:
      value: 'ddp'
    precision:
      value: 16
    
    epoch:
      value: 1

    ckpt:
      value: 'ckpt/marlin/test'